name: ptypy_workflow
channels:
  - conda-forge
dependencies:
  - python=3.14
  - numpy
  - scipy
  - pyzmq
  - mpi4py
  - packaging
  - pillow
  - pyfftw
  - pyyaml
  - matplotlib
  - jupyter
  - nbconvert
  - papermill
  - h5py
  - pip
  - pip:
      - git+https://github.com/ptycho/ptypy@master
