on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Download dist artifact
<<<<<<< before updating
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
=======
        uses: actions/download-artifact@v8
>>>>>>> after updating
        with:
          name: dist
          path: dist

      - name: Publish to PyPI using trusted publishing
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          attestations: false
